### PR TITLE
MNT: rerender

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

I've rerendered the recipe as instructed in #26.

Here's a checklist to do before merging.
- [ ] Bump the build number if needed.

### CODE REVIEW

**Comment by ngam** [comment]
> Hi! This is the friendly automated conda-forge-linting service.
> 
> I wanted to let you know that I linted all conda-recipes in your PR (`recipe`) and found some lint.
> 
> Here's what I've got...
> 
> For **recipe**:
> 
> * Recipe maintainer "jvegasbsc" does not exist

@zklaus @valeriupredoi this needs fixing, and this also updates README:

https://github.com/conda-forge/esmvalcore-feedstock/blob/dc8922e9d3edc7480a9b5ac6519b72fa7262d129/README.md?plain=1#L125-L130

**Comment by ngam** [comment]
> Thanks @ngam. jvegasbsc changed employer and his name with it. We won't be updating the name though because as a consequence he also left the project.

Maybe just delete jvegasbsc from the maintainer list?

**Comment by zklaus** [comment]
@conda-forge-admin please rerender

**Comment by valeriupredoi** [comment]
cheers @ngam - yis, we should just delete Javi :laughing:

**Comment by ngam** [comment]
👀 you have a fancy test feedback... hopefully those xxx aren't failures ... 

```
...........................x............................................ [  2%]
....................................................................sss. [  5%]
........................................................................ [  8%]
........................................................................ [ 11%]
........................................................................ [ 14%]
........................................................................ [ 17%]
........................................................................ [ 20%]
........................................................................ [ 23%]
........................................................................ [ 26%]
........................................................................ [ 29%]
........................................................................ [ 32%]
.........................................................ss............. [ 35%]
..........ss............................................................ [ 38%]
........................................................................ [ 41%]
..........................................ss............................ [ 44%]
......................................................................... [ 47%]
........................................................................ [ 50%]
........................................................................ [ 53%]
........................................................................ [ 56%]
......................................................................... [ 59%]
........................................................................ [ 62%]
........................................................................ [ 65%]
........................................................................ [ 68%]
........................................................................ [ 71%]
........................................................................ [ 74%]
........................................................................ [ 77%]
.................................................................xxxx... [ 80%]
................X....................................................... [ 83%]
........................................................................ [ 86%]

```

**Comment by zklaus** [comment]
No, those are [`xfail`s](https://docs.pytest.org/en/latest/how-to/skipping.html)---expected fails.

**Comment by valeriupredoi** [comment]
yeah, "brush under the rug" tests :grin:

**Pull request merged**
