### PR TITLE
Pre release v2.5.0rc2

### PR DESCRIPTION
**Pull request by schlunma**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by schlunma** [comment]
Closes #19

**Comment by schlunma** [comment]
@conda-forge-admin, please rerender

**Comment by schlunma** [comment]
@zklaus @valeriupredoi is there anything else I need to do?

**Comment by zklaus** [comment]
I think that's all. We'll just have to wait for the infrastructure to come back to see the tests go through and do the final review.

**Review by valeriupredoi — APPROVED** [review]

**Comment by valeriupredoi** [comment]
looking good, cheers @schlunma and @zklaus :+1: I am a bit concerned by the use of `boa` - I don't fully understand the context in which it's used, but I know a few months ago `boa` was not up to the job (well, neither was `conda` for the matter), but since that's part of the auto build am gonna trust the conda folk

**Comment by schlunma** [comment]
@conda-forge-admin, please rerender

**Comment by zklaus** [comment]
@conda-forge-admin, please rerender

**Comment by schlunma** [comment]
Closing this, will branch off from the `rc` branch to keep the history clean and open another PR.

**Pull request closed without merging**
