### PR TITLE
Add importlib_resources to support Python 3.7 and 3.8

### PR DESCRIPTION
**Pull request by zklaus**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

We need `importlib_resources`, which is part of the standard library, but only from Python 3.9 onward. To make sure things work with older Python versions, we add the package as a dependency here.

### CODE REVIEW

**Comment by zklaus** [comment]
@conda-forge-admin, please rerender

**Comment by valeriupredoi** [comment]
:eyes:

**Comment by valeriupredoi** [comment]
cheers @zklaus - did them tests pas? :beer:

**Comment by zklaus** [comment]
You can check for yourself: In the little row above where it says "zklaus merged commit..." with the little merge icon on the left, there is a button on the right labeled "View details".

But yes, of course I waited for the checks :wink:

**Comment by valeriupredoi** [comment]
ach so, I forgot about that little button :grin: Let's see the GA tests pass at our end now :beer:

**Comment by zklaus** [comment]
Hold your horses. Now it's in the queue to be build in `master`. That will take about 20 mins. Then it needs to be uploaded and distributed in the CDN---another 90 to 120 mins.

**Comment by valeriupredoi** [comment]
:horse: I meant the nightly ones that run (I believe) at 4am GMT, if conda's not done by then I will personally tell her to hurry the [] up :grin:

**Comment by zklaus** [comment]
It seems to have done the trick :smile: :beers:

**Comment by valeriupredoi** [comment]
it did indeed, man! All is biutiful and correct :clap:

**Pull request merged**
