### PR TITLE
Version v2.11.1

### PR DESCRIPTION
**Pull request by valeriupredoi**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* ~[ ] Bumped the build number (if the version is unchanged)~
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes https://github.com/conda-forge/esmvalcore-feedstock/pull/80

### CODE REVIEW

**Comment by valeriupredoi** [comment]
@conda-forge-admin, please rerender

**Comment by valeriupredoi** [comment]
@conda-forge-admin, please rerender

**Comment by schlunma** [comment]
Awesome, thanks V!! Looks good to me. Do we want to do anything regarding those two comments by the bot:

> ℹ️ No valid build backend found for Python recipe for package esmvalcore using pip. Python recipes using pip need to explicitly specify a build backend in the host section. If your recipe has built with only pip in the host section in the past, you likely should add setuptools to the host section of your recipe.

> ℹ️ noarch: python recipes should usually follow the syntax in our [documentation](https://conda-forge.org/docs/maintainer/knowledge_base/#noarch-python) for specifying the Python version.
        For the host section of the recipe, you should usually use python {{ python_min }} for the python entry.
        For the run section of the recipe, you should usually use python >={{ python_min }} for the python entry.
        For the test.requires section of the recipe, you should usually use python {{ python_min }} for the python entry.
        If the package requires a newer Python version than the currently supported minimum version on conda-forge, you can override the python_min variable by adding a Jinja2 set statement at the top of your recipe (or using an equivalent context variable for v1 recipes).

**Comment by valeriupredoi** [comment]
we may want to change the way we specify the Python pins in the various sections, to comply with the new syntax, but we can do that for 2.12, about `setuptools` - we have `setuptools_scm` and that is there. I think we can get this in now :+1: @bouweandela you want to have a lookover and merge, pls, bud :beer:

**Review by schlunma — APPROVED** [review]
Cheers, thanks V!! 🚀

**Comment by valeriupredoi** [comment]
> I'd recommend just fixing the things raised by the bot

Aye, will plop them in here then, the day we start listening to robots is upon us, gents 🤖 😁

**Comment by valeriupredoi** [comment]
OK the `{{ python_min }}` thing is actually a BAD constraint: it comes from [CFEP25](https://github.com/conda-forge/cfep/blob/main/cfep-25.md) - it makes things a lot easier for conda-forge people, but degrades the user's control over the package, setting the variable in the `conda_forge.yml` file can be easily overlooked when someone with less experience comes along and does the release/build; I also don't see any mention of `{{ python_max }}` that we need (ie pin to >3.13 here). What did they think when they came up with this idea?

**Comment by valeriupredoi** [comment]
OK [built well](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=1092425&view=logs&j=7b6f2c87-f3a7-5133-8d84-7c03a75d9dfc&t=9eb77fd2-8ddd-5444-8fc0-71cb28dcb736) - scroll down to see the environment: all nice and clean, and Python-y 3.12-y too, am merging this :beer:

**Pull request merged**
