### PR TITLE
esmvalcore v2.8.1

### PR DESCRIPTION
**Pull request by valeriupredoi**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* ~[ ] Bumped the build number (if the version is unchanged)~
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This supersedes the regro-bot autotick PR, that needs be closed as soon as the bot opens it. We did it this way to speed up the release and get all the correct pins from the up-to-date RC release.

### CODE REVIEW

**Comment by valeriupredoi** [comment]
@conda-forge-admin, please rerender

**Comment by bouweandela** [comment]
Could you also add `pytest-json-report` as a dependency to make it work with the `esmpy` 8.4.0 and 8.4.1 packages?

**Comment by bouweandela** [comment]
The point is to not break the existing ESMValTool package, which cannot be installed with the latest version (8.4.2) of `esmpy`. Since `esmpy` is a dependency of ESMValCore, it also makes sense to add it here.

**Comment by valeriupredoi** [comment]
Thought about this even more - as it is, the Core env is solid and modern, and picks up esmpy=8.4.2 (latest) - there is no reason for us to get obsolete deps in this env, when the roadblock and need for that dep comes solely from ESMValTool (the current pin on shapely<2 there) - testing should be done with an up to date env for Tool (so a 2.9.0rc1 for pure package testing)

**Comment by bouweandela** [comment]
Since we're not planning to release an ESMValTool v2.8.1, this is the best place to solve this issue. We can still update things for v2.9.0, so there will be no need to add this dependency to that (hopefully).

**Review by bouweandela — APPROVED** [review]
:beers: :beers: :beers:

**Comment by valeriupredoi** [comment]
thank you Sir @bouweandela :beer:

**Pull request merged**
