### PR TITLE
No longer install dependencies from PyPI

### LINKED ISSUE #29: Package seems to install (contain?) dependencies from PyPI
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue: When installing the package, it looks like some of the dependencies are installed from PyPI (see the output of `conda list` below) instead of from conda-forge. Could this be due to a missing `--no-deps` on this line?
https://github.com/conda-forge/esmvalcore-feedstock/blob/eee9fd042ffe27379339704497b1b2b57dd63b0f/recipe/meta.yaml#L18

That might mean that some dependencies get included with the esmvalcore package on conda-forge at build time, instead of getting installed as dependencies from conda-forge.

The command used to create this environment is
```bash
conda create -n test -c conda-forge esmvalcore
```

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /home/bandela/mambaforge/envs/test:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
antlr-python-runtime      4.7.2           py310hff52083_1003    conda-forge
antlr4-python3-runtime    4.7.2                    pypi_0    pypi
atk-1.0                   2.36.0               h3371d22_4    conda-forge
attrs                     21.4.0             pyhd8ed1ab_0    conda-forge
blosc                     1.21.0               h9c3ff4c_0    conda-forge
bokeh                     2.4.2                    pypi_0    pypi
boost-cpp                 1.74.0               h6cacc03_7    conda-forge
brotli                    1.0.9                h7f98852_6    conda-forge
brotli-bin                1.0.9                h7f98852_6    conda-forge
brotlipy                  0.7.0                    pypi_0    pypi
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2021.10.8            ha878542_0    conda-forge
cairo                     1.16.0            ha00ac49_1009    conda-forge
cartopy                   0.20.2                   pypi_0    pypi
certifi                   2021.10.8                pypi_0    pypi
cf-units                  3.0.1                    pypi_0    pypi
cffi                      1.15.0                   pypi_0    pypi
cfitsio                   4.0.0                h9a35b8e_0    conda-forge
cftime                    1.5.2                    pypi_0    pypi
charset-normalizer        2.0.12             pyhd8ed1ab_0    conda-forge
click                     8.0.4                    pypi_0    pypi
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.7.2              pyhd8ed1ab_1    conda-forge
cloudpickle               2.0.0              pyhd8ed1ab_0    conda-forge
cryptography              36.0.1                   pypi_0    pypi
curl                      7.81.0               h2574ce0_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
cytoolz                   0.11.2                   pypi_0    pypi
dask                      2022.2.0           pyhd8ed1ab_0    conda-forge
dask-core                 2022.2.0           pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
distributed               2022.2.0                 pypi_0    pypi
esgf-pyclient             0.3.0              pyh6c4a22f_1    conda-forge
esmf                      8.2.0           nompi_h61edca3_0    conda-forge
esmpy                     8.2.0                    pypi_0    pypi
esmvalcore                2.4.0              pyhd8ed1ab_2    conda-forge
expat                     2.4.6                h27087fc_0    conda-forge
fiona                     1.8.21                   pypi_0    pypi
fire                      0.4.0              pyh44b312d_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.13.96              ha180cfb_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.29.1                   pypi_0    pypi
freetype                  2.10.4               h0708190_1    conda-forge
freexl                    1.0.6                h7f98852_0    conda-forge
fribidi                   1.0.10               h36c2ea0_0    conda-forge
fsspec                    2022.2.0           pyhd8ed1ab_0    conda-forge
gdal                      3.4.1                    pypi_0    pypi
gdk-pixbuf                2.42.6               h04a7f16_0    conda-forge
geos                      3.10.2               h9c3ff4c_0    conda-forge
geotiff                   1.7.0                h6593c0a_6    conda-forge
gettext                   0.19.8.1          h73d1719_1008    conda-forge
giflib                    5.2.1                h36c2ea0_2    conda-forge
graphite2                 1.3.13            h58526e2_1001    conda-forge
graphviz                  2.50.0               h8e749b2_2    conda-forge
gtk2                      2.24.33              h90689f9_2    conda-forge
gts                       0.7.6                h64030ff_2    conda-forge
harfbuzz                  3.4.0                hb4a5f5f_0    conda-forge
hdf4                      4.2.15               h10796ff_3    conda-forge
hdf5                      1.12.1          nompi_h2750804_103    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
html5lib                  1.1                pyh9f0ad1d_0    conda-forge
humanfriendly             10.0                     pypi_0    pypi
icu                       69.1                 h9c3ff4c_0    conda-forge
idna                      3.3                pyhd8ed1ab_0    conda-forge
importlib-metadata        4.11.1                   pypi_0    pypi
importlib_resources       5.4.0              pyhd8ed1ab_0    conda-forge
iris                      3.2.0.post0        pyhd8ed1ab_0    conda-forge
isodate                   0.6.1              pyhd8ed1ab_0    conda-forge
jbig                      2.1               h7f98852_2003    conda-forge
jinja2                    3.0.3              pyhd8ed1ab_0    conda-forge
jpeg                      9e                   h7f98852_0    conda-forge
json-c                    0.15                 h98cffda_0    conda-forge
kealib                    1.4.14               h87e4c3c_3    conda-forge
kiwisolver                1.3.2                    pypi_0    pypi
krb5                      1.19.2               hcc1bbae_3    conda-forge
latexcodec                2.0.1              pyh9f0ad1d_0    conda-forge
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
lerc                      3.0                  h9c3ff4c_0    conda-forge
libblas                   3.9.0           13_linux64_openblas    conda-forge
libbrotlicommon           1.0.9                h7f98852_6    conda-forge
libbrotlidec              1.0.9                h7f98852_6    conda-forge
libbrotlienc              1.0.9                h7f98852_6    conda-forge
libcblas                  3.9.0           13_linux64_openblas    conda-forge
libcurl                   7.81.0               h2574ce0_0    conda-forge
libdap4                   3.20.6               hd7c4107_2    conda-forge
libdeflate                1.10                 h7f98852_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 11.2.0              h1d223b6_12    conda-forge
libgd                     2.3.3                h3cfcdeb_1    conda-forge
libgdal                   3.4.1                hc3d8651_3    conda-forge
libgfortran-ng            11.2.0              h69a702a_12    conda-forge
libgfortran5              11.2.0              h5c6108e_12    conda-forge
libglib                   2.70.2               h174f98d_4    conda-forge
libgomp                   11.2.0              h1d223b6_12    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
libkml                    1.3.0             h238a007_1014    conda-forge
liblapack                 3.9.0           13_linux64_openblas    conda-forge
libnetcdf                 4.8.1           nompi_hb3fd0d9_101    conda-forge
libnghttp2                1.47.0               h727a467_0    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libopenblas               0.3.18          pthreads_h8fe5266_0    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libpq                     14.2                 hd57d9b9_0    conda-forge
librsvg                   2.52.5               h0a9e6e8_2    conda-forge
librttopo                 1.1.0                hf69c175_9    conda-forge
libspatialite             5.0.1               h0e567f8_14    conda-forge
libssh2                   1.10.0               ha56f1ee_2    conda-forge
libstdcxx-ng              11.2.0              he4da1e4_12    conda-forge
libtiff                   4.3.0                h542a066_3    conda-forge
libtool                   2.4.6             h9c3ff4c_1008    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libwebp                   1.2.2                h3452ae3_0    conda-forge
libwebp-base              1.2.2                h7f98852_1    conda-forge
libxcb                    1.13              h7f98852_1004    conda-forge
libxml2                   2.9.12               h885dcf4_1    conda-forge
libxslt                   1.1.33               h0ef7038_3    conda-forge
libzip                    1.8.0                h4de3113_1    conda-forge
libzlib                   1.2.11            h36c2ea0_1013    conda-forge
locket                    0.2.0                      py_2    conda-forge
lxml                      4.8.0                    pypi_0    pypi
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
markupsafe                2.1.0                    pypi_0    pypi
matplotlib                3.5.1                    pypi_0    pypi
matplotlib-base           3.5.1           py310h23f4a51_0    conda-forge
msgpack                   1.0.3                    pypi_0    pypi
msgpack-python            1.0.3           py310h91b1402_0    conda-forge
munch                     2.5.0                      py_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
myproxyclient             2.1.0              pyhd8ed1ab_2    conda-forge
ncurses                   6.3                  h9c3ff4c_0    conda-forge
netcdf-fortran            4.5.4           nompi_h2b6e579_100    conda-forge
netcdf4                   1.5.8                    pypi_0    pypi
networkx                  2.6.3              pyhd8ed1ab_1    conda-forge
nspr                      4.32                 h9c3ff4c_1    conda-forge
nss                       3.74                 hb5efdd6_0    conda-forge
numpy                     1.22.2                   pypi_0    pypi
openjpeg                  2.4.0                hb52868f_1    conda-forge
openssl                   1.1.1l               h7f98852_0    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandas                    1.4.1                    pypi_0    pypi
pango                     1.50.3               h9967ed3_0    conda-forge
partd                     1.2.0              pyhd8ed1ab_0    conda-forge
pcre                      8.45                 h9c3ff4c_0    conda-forge
pillow                    9.0.1                    pypi_0    pypi
pip                       22.0.3             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h36c2ea0_0    conda-forge
poppler                   22.01.0              ha39eefc_0    conda-forge
poppler-data              0.4.11               hd8ed1ab_0    conda-forge
postgresql                14.2                 h2510834_0    conda-forge
proj                      8.2.1                h277dcde_0    conda-forge
prov                      2.0.0              pyhd3deb0d_0    conda-forge
psutil                    5.9.0                    pypi_0    pypi
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pybtex                    0.24.0             pyhd8ed1ab_2    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pydot                     1.4.2                    pypi_0    pypi
pyopenssl                 22.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.7              pyhd8ed1ab_0    conda-forge
pyproj                    3.3.0                    pypi_0    pypi
pyshp                     2.2.0              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1                    pypi_0    pypi
python                    3.10.2          h85951f9_3_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-stratify           0.2.post0       py310h96516ba_1    conda-forge
python-xxhash             2.0.2           py310h6acc77f_1    conda-forge
python_abi                3.10                    2_cp310    conda-forge
pytz                      2021.3             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0                      pypi_0    pypi
rdflib                    6.1.1              pyhd8ed1ab_0    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
requests                  2.27.1             pyhd8ed1ab_0    conda-forge
requests_cache            0.4.13                     py_0    conda-forge
scipy                     1.8.0                    pypi_0    pypi
setuptools                59.8.0                   pypi_0    pypi
shapely                   1.8.0                    pypi_0    pypi
six                       1.16.0             pyh6c4a22f_0    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
sqlite                    3.37.0               h9cd32fc_0    conda-forge
stratify                  0.2.post0                pypi_0    pypi
tblib                     1.7.0              pyhd8ed1ab_0    conda-forge
termcolor                 1.1.0                      py_2    conda-forge
tiledb                    2.6.2                h2038895_1    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
toolz                     0.11.2             pyhd8ed1ab_0    conda-forge
tornado                   6.1                      pypi_0    pypi
typing_extensions         4.1.1              pyha770c72_0    conda-forge
tzcode                    2021e                h7f98852_0    conda-forge
tzdata                    2021e                he74cb21_0    conda-forge
udunits2                  2.2.28               hc3e0081_0    conda-forge
unicodedata2              14.0.0                   pypi_0    pypi
urllib3                   1.26.8             pyhd8ed1ab_1    conda-forge
webencodings              0.5.1                      py_1    conda-forge
webob                     1.8.7              pyhd8ed1ab_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xerces-c                  3.2.3                h8ce2273_4    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.0.10               h7f98852_0    conda-forge
xorg-libsm                1.2.3             hd9c2040_1000    conda-forge
xorg-libx11               1.7.2                h7f98852_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h7f98852_1    conda-forge
xorg-libxrender           0.9.10            h7f98852_1003    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h7f98852_1002    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xxhash                    2.0.2                    pypi_0    pypi
xz                        5.2.5                h516909a_1    conda-forge
yamale                    4.0.3              pyh6c4a22f_0    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
zict                      2.0.0                      py_0    conda-forge
zipp                      3.7.0              pyhd8ed1ab_1    conda-forge
zlib                      1.2.11            h36c2ea0_1013    conda-forge
zstd                      1.5.2                ha95c52a_0    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : test
    active env location : /home/bandela/mambaforge/envs/test
            shell level : 2
       user config file : /home/bandela/.condarc
 populated config files : /home/bandela/mambaforge/.condarc
                          /home/bandela/.condarc
          conda version : 4.10.3
    conda-build version : not installed
         python version : 3.9.7.final.0
       virtual packages : __linux=5.13.0=0
                          __glibc=2.34=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/bandela/mambaforge  (writable)
      conda av data dir : /home/bandela/mambaforge/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /home/bandela/mambaforge/pkgs
                          /home/bandela/.conda/pkgs
       envs directories : /home/bandela/mambaforge/envs
                          /home/bandela/.conda/envs
               platform : linux-64
             user-agent : conda/4.10.3 requests/2.26.0 CPython/3.9.7 Linux/5.13.0-30-generic ubuntu/21.10 glibc/2.34
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

```
</details>

### PR DESCRIPTION
**Pull request by bouweandela**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* ~[ ] Reset the build number to `0` (if the version changed)~
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Fix #29

### CODE REVIEW

**Comment by bouweandela** [comment]
@conda-forge-admin, please rerender

**Review by zklaus — APPROVED** [review]
Good catch, thanks Bouwe!

**Comment by zklaus** [comment]
@schlunma, could you integrate this also in the rc branch when you are cutting the next rc?

**Comment by schlunma** [comment]
Yes! Please remind me of that in case I forget this :sweat_smile:

**Pull request merged**
