### PR TITLE
Release candidate RC2 esmvalcore=2.8.1rc2

### PR DESCRIPTION
**Pull request by valeriupredoi**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* ~[ ] Bumped the build number (if the version is unchanged)~
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Pin libnetcdf != 4.9.1 to avoid HDF5 warnings (as done by @bouweandela in #63 )
Closes #63

### CODE REVIEW

**Comment by valeriupredoi** [comment]
@bouweandela if we plop the pin on `libnetcdf` here then we can close https://github.com/conda-forge/esmvalcore-feedstock/pull/63

**Comment by valeriupredoi** [comment]
@conda-forge-admin, please rerender

**Comment by valeriupredoi** [comment]
ready to go :checkered_flag:

**Review by bouweandela — APPROVED** [review]
Thanks @valeriupredoi!

**Comment by valeriupredoi** [comment]
thank you @bouweandela :beer:

**Pull request merged**
