### PR TITLE
Pre release v2.5.0rc3

### PR DESCRIPTION
**Pull request by schlunma**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by schlunma** [comment]
@conda-forge-admin, please rerender

**Review by valeriupredoi — APPROVED** [review]
looking good, Manu, cheers!

**Comment by schlunma** [comment]
Can you merge this? I still don't have the rights.

**Comment by valeriupredoi** [comment]
just did - let me have a look at the repo permissions for you, man

**Pull request merged**
