### PR TITLE
Pre-release condidate for v2.7.0rc2

### PR DESCRIPTION
**Pull request by valeriupredoi**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by valeriupredoi** [comment]
@conda-forge-admin, please rerender

**Comment by valeriupredoi** [comment]
@conda-forge-admin, please rerender

**Comment by valeriupredoi** [comment]
I folded in https://github.com/conda-forge/esmvalcore-feedstock/issues/48 but will close that issue only when we have release 2.7.0 stable :+1:

**Comment by valeriupredoi** [comment]
Ok good stuff - rendering and builds passed a-ok, could I get an approve please @sloosvel @schlunma @zklaus - we have us an initial decent package :beer:

**Comment by schlunma** [comment]
Does it make sense to release this given https://github.com/ESMValGroup/ESMValCore/issues/1747? We could move straight to `v2.7.0.rc2` (I think we had to do this for the previous release as well 😬).

**Comment by valeriupredoi** [comment]
> [ESMValGroup/ESMValCore#1748](https://github.com/ESMValGroup/ESMValCore/pull/1748) is ready and seems to fix the problem +1

that is indeed brilliant! I'll get us an rc2 then with that in asap - also https://github.com/ESMValGroup/ESMValCore/pull/1749 needs in so we don't pick up somebody else's failed dox badge :grin:  :beer:

**Comment by valeriupredoi** [comment]
bummer! Github decided to go belly up, Actions are degraded, not safe to make a release this evening, will do it in the morning - Saskia is not launching tests at this late hour anyway (I hope :grin: )

**Comment by valeriupredoi** [comment]
btw don't close this - am simply gonna change to rc2 here :hammer:

**Comment by valeriupredoi** [comment]
@conda-forge-admin, please rerender

**Comment by valeriupredoi** [comment]
how very nice - I've cooked me some dinner and cooked us up a conda package (this time round all clean and green), guys please approve :hamburger: please

**Review by sloosvel — APPROVED** [review]

**Comment by valeriupredoi** [comment]
very many thanks @sloosvel :beer:

**Pull request merged**
