### PR TITLE
Release candidate RC1 esmvalcore=2.8.1rc1

### PR DESCRIPTION
**Pull request by valeriupredoi**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
~* [ ] Bumped the build number (if the version is unchanged)~
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by valeriupredoi** [comment]
@conda-forge-admin, please rerender

**Comment by valeriupredoi** [comment]
@bouweandela I noticed we have a set of quite restrictive (well, lower bounds) pins for a number of packages from the pytesting zone, and we never bothered plopping those pins in here, shall I bring them in so we are exactly at the same pins as upstream?

**Comment by valeriupredoi** [comment]
> I wouldn't bother unless you run into trouble. By default you'll get the latest of everything anyway.

yeh that's what I thought too, but now, as a responsible maintainer of various dubious packages across c-f, I thought I'd be a bit more tidy about that :grin:

**Comment by valeriupredoi** [comment]
huzzah! Tests pass - can I get a review please :beer:

**Review by bouweandela — APPROVED** [review]

**Pull request merged**
